// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzsSVMCN-Z2_OUYyzvJjiWz4jc2BpQPck',
    appId: '1:837471827346:web:26a2142ff535c1bcfe7d4b',
    messagingSenderId: '837471827346',
    projectId: 'poetic-ceremony-345507',
    authDomain: 'poetic-ceremony-345507.firebaseapp.com',
    databaseURL: 'https://poetic-ceremony-345507-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poetic-ceremony-345507.appspot.com',
    measurementId: 'G-TWW6TNLVP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jaPF_w3ysDqEavetUOYcVxVHw3EnqrI',
    appId: '1:837471827346:android:7b45ade956910f60fe7d4b',
    messagingSenderId: '837471827346',
    projectId: 'poetic-ceremony-345507',
    databaseURL: 'https://poetic-ceremony-345507-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poetic-ceremony-345507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbOW_fB7Cy4AC4jp1YET1ItgaZhFpWSGQ',
    appId: '1:837471827346:ios:c7819b7119901198fe7d4b',
    messagingSenderId: '837471827346',
    projectId: 'poetic-ceremony-345507',
    databaseURL: 'https://poetic-ceremony-345507-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poetic-ceremony-345507.appspot.com',
    androidClientId: '837471827346-49l9u51q7g26ad44culc7fu6q5tqlrn9.apps.googleusercontent.com',
    iosClientId: '837471827346-ro3hhmu327f4rquvovrrgvklb49jqgjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBuscadorAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbOW_fB7Cy4AC4jp1YET1ItgaZhFpWSGQ',
    appId: '1:837471827346:ios:c7819b7119901198fe7d4b',
    messagingSenderId: '837471827346',
    projectId: 'poetic-ceremony-345507',
    databaseURL: 'https://poetic-ceremony-345507-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poetic-ceremony-345507.appspot.com',
    androidClientId: '837471827346-49l9u51q7g26ad44culc7fu6q5tqlrn9.apps.googleusercontent.com',
    iosClientId: '837471827346-ro3hhmu327f4rquvovrrgvklb49jqgjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBuscadorAnime',
  );
}
